name: Google Cloud Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud authentication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Configure Docker to authenticate to Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: europe-west1-docker.pkg.dev/isen-python-458209/isen-python-repo:latest
          cache-from: europe-west1-docker.pkg.dev/isen-python-458209/isen-python-repo:latest
          cache-to: type=inline

      - name: Push Docker image to Artifact Registry
        run: |
          docker push larryjason/isen-python:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: isen-python   
          image: europe-west1-docker.pkg.dev/isen-python-458209/isen-python-repo:latest
          region: europe-west1
          project_id: isen-python-458209