name: Hadolint Dockerfile Linting

on:
  push:
    paths:
      - '**/Dockerfile'
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/hadolint

      - name: Run Hadolint with failure threshold set to warning
        run: |
          find . -name 'Dockerfile' -print0 | xargs -0 -n1 hadolint --failure-threshold warning
