# .github/workflows/zap_scan.yml
name: ZAP Baseline Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    name: Run ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Django server in background
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10  

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://0.0.0.0:8080'
          cmd_options: '-t 60 -m 1 -r zap_report.html -J zap_report.json'

      - name: Upload ZAP JSON report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: zap-json-report
          path: zap_report.json

      - name: Upload ZAP HTML report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: zap-html-report
          path: zap_report.html
